tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'sanemat/font'
# tap 'homebrew/binary'
# tap 'homebrew/boneyard'
# tap 'homebrew/dupes'
# tap 'homebrew/science'
# tap 'homebrew/services'
# tap 'homebrew/versions'
# tap 'neovim/neovim'

brew 'autoconf'
brew 'automake'
brew 'autogen'
brew 'aws-elasticbeanstalk'
brew 'awscli'
brew 'coreutils'
brew 'csshx'
brew 'ctags'
brew 'direnv'
brew 'elixir'
brew 'erlang'
brew 'findutils'
brew 'ghq'
brew 'git'
brew 'git-archive-all'
brew 'git-lfs'
brew 'go'
brew 'growly'
brew 'httpie'
brew 'hub'
brew 'jq'
brew 'libxml2'
brew 'libxslt'
brew 'lua'
brew 'luajit'
# brew 'macvim', args: ['with-lua', 'with-luajit']
brew 'mas'
brew 'mercurial'
brew 'mobile-shell'
brew 'moreutils'
brew 'open-cobol'
brew 'mysql'
brew 'nkf'
brew 'node'
brew 'nodenv'
brew 'nspr'
brew 'open-cobol'
brew 'peco'
brew 'postgresql', restart_service: true
brew 'pstree'
brew 'python'
brew 'python3'
brew 'qt@5.5'
brew 'qt'
brew 'reattach-to-user-namespace'
brew 'ruby'
brew 'ruby-build'
brew 'sqlite'
brew 'terminal-notifier'
brew 'terraform'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'vim', args: ['with-lua', 'with-luajit']
brew 'wget'
brew 'yarn'
# brew 'zplug'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-lovers'
# brew 'fish'
brew 'sanemat/font/ricty', args: ['with-powerline']

# brew 'apple-gcc42'
# brew 'apr'
# brew 'apr-util'
# brew 'boost'
# brew 'freetype'
# brew 'fontconfig'
# brew 'gettext'
# brew 'glib'
# brew 'pixman'
# brew 'cairo'
# brew 'chromedriver'
# brew 'cscope'
# brew 'jpeg'
# brew 'wxmac'
# brew 'erlang'
# brew 'elixir'
# brew 'embulk'
# brew 'gobject-introspection'
# brew 'icu4c'
# brew 'harfbuzz'
# brew 'libtool'
# brew 'pango'
# brew 'fontforge'
# brew 'gmp'
# brew 'isl'
# brew 'mpfr'
# brew 'libmpc'
# brew 'gcc'
# brew 'gd'
# brew 'gdb'
# brew 'git-flow'
# brew 'graphviz'
# brew 'httperf'
# brew 'xz'
# brew 'imagemagick'
# brew 'oniguruma'
# brew 'lame'
# brew 'libevent'
# brew 'memcached'
# brew 'libmemcached'
# brew 'libsodium'
# brew 'libvo-aacenc'
# brew 'libyaml'
# brew 'ncurses'
# brew 'ossp-uuid'
# brew 'pandoc'
# brew 'phantomjs'
# brew 'plantuml'
# brew 'pngquant'
# brew 'postgresql@9.4'
# brew 'redis'
# brew 'snappy'
# brew 'spidermonkey'
# brew 'subversion'
# brew 'unixodbc'
# brew 'utf8proc'
# brew 'x264'
# brew 'xvid'
# brew 'neovim/neovim/neovim', args: ['HEAD']

cask 'appcleaner'
cask 'dash'
cask 'diskwave'
cask 'docker'
cask 'dropbox'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'hammerspoon'
cask 'iterm2'
cask 'libreoffice'
cask 'microsoft-office'
cask 'minecraft'
cask 'totalfinder'
cask 'macvim'

mas 'LINE', id: 539883307
mas '1Password', id: 443987910
mas 'Airmail 3', id: 918858936
mas 'BetterSnapTool', id: 417375580
mas 'CotEditor', id: 1024640650
mas 'GarageBand', id: 682658836
mas 'Keynote', id: 409183694
mas 'Mactracker', id: 430255202
mas 'Marked 2', id: 890031187
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'PopClip', id: 445189367
mas 'Slack', id: 803453959
mas 'Witch', id: 412485838
mas 'Wunderlist', id: 410628904
mas 'iMovie', id: 408981434
mas 'Xcode', id: 497799835
