tap 'caskroom/cask'
tap 'homebrew/binary'
tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'homebrew/science'
tap 'neovim/neovim'
tap 'peco/peco'
tap 'sanemat/font'
brew 'libyaml'
brew 'ansible'
brew 'autoconf'
brew 'xz'
brew 'automake'
brew 'awscli'
brew 'pcre'
brew 'gettext'
brew 'git'
brew 'go'
brew 'docker'
brew 'boot2docker'
brew 'pkg-config'
brew 'libpng'
brew 'freetype'
brew 'fontconfig'
brew 'pixman'
brew 'libffi'
brew 'glib'
brew 'cairo'
brew 'gmp'
brew 'isl'
brew 'cloog'
brew 'cmake'
brew 'coreutils'
brew 'cscope'
brew 'csshx'
brew 'ctags'
brew 'libsodium'
brew 'zeromq'
brew 'czmq'
brew 'elasticsearch'
brew 'libtool'
brew 'openssl'
brew 'unixodbc'
brew 'jpeg'
brew 'libtiff'
brew 'wxmac'
brew 'erlang'
brew 'elixir'
brew 'findutils'
brew 'icu4c'
brew 'gobject-introspection'
brew 'harfbuzz'
brew 'pango'
brew 'fontforge'
brew 'mpfr'
brew 'libmpc'
brew 'gcc'
brew 'gdbm'
brew 'ghi'
brew 'git-flow'
brew 'graphviz'
brew 'growly'
brew 'hub'
brew 'imagemagick'
brew 'lame'
brew 'libevent'
brew 'libvo-aacenc'
brew 'readline'
brew 'sqlite'
brew 'python'
brew 'libxml2'
brew 'libxslt'
brew 'lua'
brew 'luajit'
brew 'macvim', args: ['custom-icons', 'with-lua', 'with-luajit']
brew 'memcached'
brew 'mercurial'
brew 'protobuf'
brew 'mobile-shell'
brew 'mongodb'
brew 'mysql'
brew 'nkf'
brew 'node'
brew 'nspr'
brew 'ossp-uuid'
brew 'pandoc'
brew 'peco'
brew 'phantomjs'
brew 'plantuml'
brew 'pngquant'
brew 'postgresql'
brew 'pstree'
brew 'qt'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'ruby'
brew 'ruby-build'
brew 'sbt'
brew 'scala'
brew 'spidermonkey'
brew 'subversion'
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
# brew 'tokyo-cabinet'
brew 'tree'
brew 'vim', args: ['with-lua', 'with-luajit']
brew 'wget'
brew 'x264'
brew 'xvid'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-lovers'
brew 'caskroom/cask/brew-cask'
brew 'homebrew/dupes/apple-gcc42'
brew 'homebrew/dupes/gdb'
brew 'homebrew/dupes/ncurses'
brew 'neovim/neovim/neovim', args: ['HEAD']
brew 'sanemat/font/ricty'
cask 'xquartz'
# cask 'adobe-reader'
# cask 'appcleaner'
# cask 'bittorrent-sync'
# cask 'calibre'
# cask 'coteditor'
# cask 'dropbox'
# cask 'evernote'
# cask 'firefox'
# cask 'freemind'
# cask 'gimp'
# cask 'github'
# cask 'google-chrome'
# cask 'google-hangouts'
# cask 'hipchat'
# cask 'iterm2'
# cask 'karabiner'
# cask 'kobito'
# cask 'libreoffice'
# cask 'mactracker'
# cask 'seil'
# cask 'send-to-kindle'
# cask 'sequel-pro'
# cask 'sourcetree'
# cask 'spectacle'
# cask 'the-unarchiver'
# cask 'totalfinder'
# cask 'vagrant'
# cask 'virtualbox'
